[*]
sleep-idle-seconds = 1800
no-mmap = 1
mmproj-offload = off
jinja = 1

threads = 24
threads-batch = 24
mlock = 1
np = 1
kv-unified = 1
cache-reuse = 1
cache-ram = 8192
#dev = Vulkan0

# log level (uncomment for debug)
#lv = 4

[Ornith-1.0-35B-UD-Q6_K_XL]
model = ./ornith-1.0-35b-Q4_K_M.gguf
ctx-size = 10480
ctx-checkpoints = 16
ngl = -1
cpu-moe = on
#n-cpu-moe = 17
fit = off
flash-attn = on
batch-size = 2048
ubatch-size = 512
no-mmproj = 1
temp = 0.75
top-p = 0.95
top-k = 20
min-p = 0.024
repeat-penalty = 1.05
presence-penalty = 1.5
reasoning = on
reasoning-budget = -1
reasoning-format = deepseek
repeat-penalty = 1.0 
jinja = on
chat-template-file = /etc/llamacpp/templates/qwen_fixed_chat_tpl.jinja
chat-template-kwargs = {"preserve_thinking":true}
cache-type-k = q8_0
cache-type-v = turbo4
