[*]
sleep-idle-seconds = 1800
no-mmap = 1
dev = ROCm0
threads = 6
mmproj-offload = off
parallel = 1
jinja = 1
#dev = Vulkan0

[Ornith-1.0-35B-UD-Q6_K_XL]
model = ./Ornith-1.0-35B-UD-Q6_K_XL.gguf
ctx-size = 81920
ctx-checkpoints = 16
ngl = -1
n-cpu-moe = 14
flash-attn = on
batch-size = 4096
ubatch-size = 2048
no-mmproj = 1
temp = 0.75
top-p = 0.95
top-k = 20
min-p = 0.024
repeat-penalty = 1.05
presence-penalty = 1.5
reasoning = on
reasoning-budget = -1
reasoning-format = deepseek
repeat-penalty = 1.0 
jinja = on
chat-template-file = /etc/llamacpp/templates/qwen_fixed_chat_tpl.jinja
chat-template-kwargs = {"preserve_thinking":true}
cache-type-k = q8_0
cache-type-v = turbo4

[Qwen3.6-27B-UD-Q4_K_XL]
model = ./Qwen3.6-27B-UD-Q4_K_XL.gguf
mmproj = ./Qwen3.6-mmproj.gguf
ctx-size = 81920
ctx-checkpoints = 16
ngl = -1
# np = 1
# spec-type = draft-mtp
# spec-draft-n-max = 3
no-mmproj = on
flash-attn = on
batch-size = 4096
ubatch-size = 2048
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.0 
reasoning = on
reasoning-budget = -1
chat-template-kwargs = {"preserve_thinking":true}
cache-type-k = q8_0
cache-type-v = turbo4

[Gemma-4-31B-it-UD-Q4_K_XL]
model = ./gemma-4-31B-it-UD-Q4_K_XL.gguf
; mmproj = ./gemma-4-mmproj-BF16.gguf
ctx-size = 16384
ctx-checkpoints = 16
; ngl = -1
fit = on
fit-target = 2048
flash-attn = off
batch-size = 4096
ubatch-size = 2048
temp = 1.0
min-p = 0.01
top-p = 0.95
top-k = 64
;cache-type-k = q8_0
;cache-type-v = turbo4

