; Tuned configs for: AMD 7900XTX ;) 

[*]
sleep-idle-seconds = 1800
;dev = ROCm0
dev = Vulkan0
jinja = 1
;load-mode = mlock
mmproj-offload = off
threads = 24
threads-batch = 24
np = 2
kv-unified = 1
cache-reuse = 1
cache-ram = 8192

# log level (uncomment for debug)
#lv = 4

[Qwen3.8-27B-ColdFus-V1.1-Q4]
model = ./Qwen3.8-27B-Cold-Fusion-GAIN-V1.1-NM-DAU-NEO-MAX-NEO-MTP-Q4_K_M.gguf
mmproj = ./Qwen3.8-mmproj-BF16.gguf
no-mmproj-offload = on
; no-mmproj = on
ctx-size = 131072
;ctx-size = 86016
ctx-checkpoints = 16
fit = off
ngl = -1
load-mode = mlock
spec-type = draft-mtp
spec-draft-n-max = 2
flash-attn = on
batch-size = 2048
ubatch-size = 1024
image-min-tokens = 1024
image-max-tokens = 2048
temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.0 
reasoning = on
reasoning-format = deepseek
reasoning-preserve = 1
chat-template-file = /etc/llamacpp/templates/qwen_fixed_chat_tpl.jinja
chat-template-kwargs = {"preserve_thinking":true}
cache-type-k = q8_0
cache-type-v = q5_1
; cache-type-v = turbo4

[Muse-Glimmer-30B-UD-Q5]
model = ./Muse-Glimmer-30B-UD-Q5_K_M.gguf
model-draft = ./Muse-Glimmer-dflash-kquant.gguf
ctx-size = 131072
ctx-checkpoints = 16
; ngl = -1
; n-cpu-moe = 17
load-mode = mlock
fit = off
spec-type = draft-dflash
spec-draft-n-max = 3
flash-attn = on
batch-size = 2048
ubatch-size = 512
no-mmproj = 1
temp = 1.0
top-p = 0.95
top-k = 64
repeat-penalty = 1.05
presence-penalty = 1.5
reasoning = on
reasoning-budget = -1
repeat-penalty = 1.0 
jinja = on
cache-type-k = q8_0
cache-type-v = q5_1
; cache-type-v = turbo4

# Qwen 3.6 35B MoE-based enhanced model
[Ornith-1.0-35B-UD-Q6]
model = ./Ornith-1.0-35B-UD-Q6_K_XL.gguf
ctx-size = 81920
ctx-checkpoints = 16
; ngl = -1
load-mode = mlock
n-cpu-moe = 17
fit = off
flash-attn = on
batch-size = 2048
ubatch-size = 512
no-mmproj = 1
temp = 0.75
top-p = 0.95
top-k = 20
min-p = 0.024
repeat-penalty = 1.05
presence-penalty = 1.5
reasoning = on
reasoning-budget = -1
reasoning-format = deepseek
repeat-penalty = 1.0 
jinja = on
chat-template-file = /etc/llamacpp/templates/qwen_fixed_chat_tpl.jinja
chat-template-kwargs = {"preserve_thinking":true}
cache-type-k = q8_0
cache-type-v = q5_1
; cache-type-v = turbo4

[Qwen3-VL-8B-Instruct-UD-Q8_K_XL]
model = ./Qwen3-VL-8B-Instruct-UD-Q8_K_XL.gguf
mmproj = ./Qwen3-VL-mmproj-BF16.gguf
load-mode = mlock
no-mmproj-offload = 0
ctx-size = 32768
ctx-checkpoints = 16
image-min-tokens = 1024
image-max-tokens = 2048
ngl = 99
fit = off
flash-attn = on
batch-size = 4096
ubatch-size = 4096
temp = 0.7
top-p = 0.8
top-k = 20
min-p =  0.0
presence-penalty = 1.5
reasoning = off
jinja = on

