name: ai-llama
services:
  server:
    container_name: ai-llama-server
    image: personal/llama.cpp-rocm-gfx1100
    restart: unless-stopped
    privileged: true
    ipc: host
    shm_size: "8gb"
    security_opt:
      - seccomp=unconfined
    devices:
      - /dev/kfd
      - /dev/dri
      - /dev/mem
    cap_add:
      - CAP_SYS_ADMIN
      - SYS_PTRACE
    # group_add:
    #   - render
    ports:
      - "${LLAMA_HOST_BIND:-127.0.0.1}:${LLAMA_HOST_PORT:-11444}:11444"
    volumes:
      # Host-mounted models
      - ${LLAMA_HOST_MODELS_DIR}:/models:ro
      - ./config/:/etc/llamacpp/:ro
    networks:
      - ai-agents
    environment:
      HIP_VISIBLE_DEVICES: "0,1"
      GGML_VK_VISIBLE_DEVICES: "0"
    env_file: .env
    command: [
      "llama-server", "--host", "0.0.0.0", "--port", "11444",
      "--models-preset", "/etc/llamacpp/models.ini"
    ]

networks:
  ai-agents:
    name: ai-agents-net
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
      com.docker.network.bridge.name: "d-ai-net"

